export const flights = [
  [
    {
      airlineCode: "TS",
      route: "YYZ-YUL",
      flightNumber: "TS101",
      type: "J",
      date: "Sep 09",
      departure: "07:30",
      arrival: "08:45",
      depStation: "YYZ",
      arrStation: "YUL",
      status: "Scheduled",
      acType: "A321",
      acReg: "C-GTSA",
      groundTime: "1h 15m",
      plan: "Meal Plan A",
      paxTotal: 180,
      pax: {
        first: "0/0",
        business: "16/16",
        premium: "24/24",
        economy: "140/140",
      },
    },
    {
      airlineCode: "TS",
      route: "YUL-YYZ",
      flightNumber: "TS102",
      type: "J",
      date: "Sep 09",
      departure: "10:15",
      arrival: "11:30",
      depStation: "YUL",
      arrStation: "YYZ",
      status: "On Time",
      acType: "A321",
      acReg: "C-GTSA",
      groundTime: "1h 10m",
      plan: "Meal Plan A",
      paxTotal: 178,
      pax: {
        first: "0/0",
        business: "16/16",
        premium: "22/24",
        economy: "140/140",
      },
    },
  ],
  [
    {
      airlineCode: "TS",
      route: "YYZ-YVR",
      flightNumber: "TS201",
      type: "J",
      date: "Sep 10",
      departure: "09:00",
      arrival: "11:30",
      depStation: "YYZ",
      arrStation: "YVR",
      status: "Scheduled",
      acType: "A330",
      acReg: "C-GTSB",
      groundTime: "2h 00m",
      plan: "Meal Plan B",
      paxTotal: 300,
      pax: {
        first: "0/0",
        business: "24/24",
        premium: "36/36",
        economy: "240/240",
      },
    },
    {
      airlineCode: "TS",
      route: "YVR-YYZ",
      flightNumber: "TS202",
      type: "J",
      date: "Sep 10",
      departure: "13:30",
      arrival: "21:30",
      depStation: "YVR",
      arrStation: "YYZ",
      status: "On Time",
      acType: "A330",
      acReg: "C-GTSB",
      groundTime: "1h 50m",
      plan: "Meal Plan B",
      paxTotal: 298,
      pax: {
        first: "0/0",
        business: "24/24",
        premium: "34/36",
        economy: "240/240",
      },
    },
  ],
  [
    {
      airlineCode: "TS",
      route: "YUL-YYC",
      flightNumber: "TS301",
      type: "J",
      date: "Sep 10",
      departure: "06:45",
      arrival: "09:45",
      depStation: "YUL",
      arrStation: "YYC",
      status: "Delayed",
      acType: "A321",
      acReg: "C-GTSC",
      groundTime: "1h 30m",
      plan: "Meal Plan A",
      paxTotal: 185,
      pax: {
        first: "0/0",
        business: "16/16",
        premium: "24/24",
        economy: "145/145",
      },
    },
    {
      airlineCode: "TS",
      route: "YYC-YUL",
      flightNumber: "TS302",
      type: "J",
      date: "Sep 10",
      departure: "11:30",
      arrival: "17:30",
      depStation: "YYC",
      arrStation: "YUL",
      status: "Cancelled",
      acType: "A321",
      acReg: "C-GTSC",
      groundTime: "1h 40m",
      plan: "Meal Plan A",
      paxTotal: 183,
      pax: {
        first: "0/0",
        business: "16/16",
        premium: "22/24",
        economy: "145/145",
      },
    },
  ],
  [
    {
      airlineCode: "TS",
      route: "YYZ-CUN",
      flightNumber: "TS401",
      type: "J",
      date: "Sep 11",
      departure: "08:15",
      arrival: "12:00",
      depStation: "YYZ",
      arrStation: "CUN",
      status: "Scheduled",
      acType: "A321",
      acReg: "C-GTSD",
      groundTime: "1h 20m",
      plan: "Meal Plan C",
      paxTotal: 190,
      pax: {
        first: "0/0",
        business: "16/16",
        premium: "24/24",
        economy: "150/150",
      },
    },
    {
      airlineCode: "TS",
      route: "CUN-YYZ",
      flightNumber: "TS402",
      type: "J",
      date: "Sep 11",
      departure: "13:30",
      arrival: "17:30",
      depStation: "CUN",
      arrStation: "YYZ",
      status: "On Time",
      acType: "A321",
      acReg: "C-GTSD",
      groundTime: "1h 35m",
      plan: "Meal Plan C",
      paxTotal: 189,
      pax: {
        first: "0/0",
        business: "16/16",
        premium: "23/24",
        economy: "150/150",
      },
    },
  ],
  [
    {
      airlineCode: "TS",
      route: "YUL-CDG",
      flightNumber: "TS501",
      type: "F",
      date: "Sep 11",
      departure: "19:00",
      arrival: "07:30+1",
      depStation: "YUL",
      arrStation: "CDG",
      status: "On Time",
      acType: "A330",
      acReg: "C-GTSE",
      groundTime: "2h 10m",
      plan: "Meal Plan D",
      paxTotal: 320,
      pax: {
        first: "0/0",
        business: "28/28",
        premium: "40/40",
        economy: "252/252",
      },
    },
    {
      airlineCode: "TS",
      route: "CDG-YUL",
      flightNumber: "TS502",
      type: "F",
      date: "Sep 12",
      departure: "11:00",
      arrival: "14:30",
      depStation: "CDG",
      arrStation: "YUL",
      status: "Scheduled",
      acType: "A330",
      acReg: "C-GTSE",
      groundTime: "2h 20m",
      plan: "Meal Plan D",
      paxTotal: 318,
      pax: {
        first: "0/0",
        business: "28/28",
        premium: "38/40",
        economy: "252/252",
      },
    },
  ],
  [
    {
      airlineCode: "TS",
      route: "YYZ-YYT",
      flightNumber: "TS601",
      type: "J",
      date: "Sep 12",
      departure: "06:00",
      arrival: "10:30",
      depStation: "YYZ",
      arrStation: "YYT",
      status: "Scheduled",
      acType: "A321",
      acReg: "C-GTSF",
      groundTime: "1h 25m",
      plan: "Meal Plan A",
      paxTotal: 175,
      pax: {
        first: "0/0",
        business: "16/16",
        premium: "24/24",
        economy: "135/135",
      },
    },
    {
      airlineCode: "TS",
      route: "YYT-YYZ",
      flightNumber: "TS602",
      type: "J",
      date: "Sep 12",
      departure: "12:00",
      arrival: "14:30",
      depStation: "YYT",
      arrStation: "YYZ",
      status: "On Time",
      acType: "A321",
      acReg: "C-GTSF",
      groundTime: "1h 30m",
      plan: "Meal Plan A",
      paxTotal: 173,
      pax: {
        first: "0/0",
        business: "16/16",
        premium: "22/24",
        economy: "135/135",
      },
    },
  ],
  [
    {
      airlineCode: "TS",
      route: "YUL-LGW",
      flightNumber: "TS701",
      type: "F",
      date: "Sep 13",
      departure: "18:00",
      arrival: "06:30+1",
      depStation: "YUL",
      arrStation: "LGW",
      status: "Scheduled",
      acType: "A330",
      acReg: "C-GTSG",
      groundTime: "2h 30m",
      plan: "Meal Plan E",
      paxTotal: 315,
      pax: {
        first: "0/0",
        business: "28/28",
        premium: "36/40",
        economy: "251/252",
      },
    },
    {
      airlineCode: "TS",
      route: "LGW-YUL",
      flightNumber: "TS702",
      type: "F",
      date: "Sep 14",
      departure: "12:30",
      arrival: "15:00",
      depStation: "LGW",
      arrStation: "YUL",
      status: "On Time",
      acType: "A330",
      acReg: "C-GTSG",
      groundTime: "2h 15m",
      plan: "Meal Plan E",
      paxTotal: 314,
      pax: {
        first: "0/0",
        business: "28/28",
        premium: "36/40",
        economy: "250/252",
      },
    },
  ],
  [
    {
      airlineCode: "TS",
      route: "YYZ-CUN",
      flightNumber: "TS801",
      type: "J",
      date: "Sep 14",
      departure: "09:45",
      arrival: "13:30",
      depStation: "YYZ",
      arrStation: "CUN",
      status: "Scheduled",
      acType: "A321",
      acReg: "C-GTSH",
      groundTime: "1h 20m",
      plan: "Meal Plan C",
      paxTotal: 188,
      pax: {
        first: "0/0",
        business: "16/16",
        premium: "24/24",
        economy: "148/148",
      },
    },
    {
      airlineCode: "TS",
      route: "CUN-YYZ",
      flightNumber: "TS802",
      type: "J",
      date: "Sep 14",
      departure: "15:00",
      arrival: "19:00",
      depStation: "CUN",
      arrStation: "YYZ",
      status: "On Time",
      acType: "A321",
      acReg: "C-GTSH",
      groundTime: "1h 25m",
      plan: "Meal Plan C",
      paxTotal: 187,
      pax: {
        first: "0/0",
        business: "16/16",
        premium: "23/24",
        economy: "148/148",
      },
    },
  ],
  [
    {
      airlineCode: "TS",
      route: "YUL-MAD",
      flightNumber: "TS901",
      type: "F",
      date: "Sep 15",
      departure: "20:30",
      arrival: "09:15+1",
      depStation: "YUL",
      arrStation: "MAD",
      status: "Scheduled",
      acType: "A330",
      acReg: "C-GTSI",
      groundTime: "2h 40m",
      plan: "Meal Plan F",
      paxTotal: 322,
      pax: {
        first: "0/0",
        business: "28/28",
        premium: "40/40",
        economy: "254/254",
      },
    },
    {
      airlineCode: "TS",
      route: "MAD-YUL",
      flightNumber: "TS902",
      type: "F",
      date: "Sep 16",
      departure: "11:30",
      arrival: "14:15",
      depStation: "MAD",
      arrStation: "YUL",
      status: "On Time",
      acType: "A330",
      acReg: "C-GTSI",
      groundTime: "2h 35m",
      plan: "Meal Plan F",
      paxTotal: 320,
      pax: {
        first: "0/0",
        business: "28/28",
        premium: "40/40",
        economy: "252/254",
      },
    },
  ],
];
