export const sampleFoodOrders = [
  {
    station: "MCT",
    flight: "WY843",
    seat: "39A*F",
    passenger: "JUBEI CALVERT",
    sku: "AVML",
    cabin: "Economy",
    name: "Asian Veg Meal",
    ordered: 1,
    distributed: 0,
    loaded: 0,
  },
  {
    station: "MCT",
    flight: "WY843",
    seat: "46D*F",
    passenger: "MALIK MANS",
    sku: "VGML",
    cabin: "Economy",
    name: "Vegan Meal",
    ordered: 1,
    distributed: 0,
    loaded: 0,
  },
  {
    station: "MNL",
    flight: "WY844",
    seat: "12K F",
    passenger: "HANA MOSTAFA",
    sku: "VGML",
    cabin: "Business",
    name: "Vegan Meal",
    ordered: 1,
    distributed: 0,
    loaded: 0,
  },
  {
    station: "MNL",
    flight: "WY844",
    seat: "28D F",
    passenger: "VIOLE ABLETES",
    sku: "DBML",
    cabin: "Economy",
    name: "Diabetic Meal",
    ordered: 1,
    distributed: 0,
    loaded: 0,
  },
  {
    station: "MNL",
    flight: "WY844",
    seat: "42F",
    passenger: "JOHAR WEBER",
    sku: "VJML",
    cabin: "Economy",
    name: "Vegetarian Jain Meal",
    ordered: 1,
    distributed: 0,
    loaded: 0,
  },
];
