export const samplePreparations = [
  {
    stowage: "101T",
    carrier: "JC Headsets X12",
    equipment: "Atlas Small Unit Aluminum",
    preparedBy: "Dry Stores",
  },
  {
    stowage: "101B",
    carrier: "Ice",
    equipment: "Atlas Small Unit Aluminum",
    preparedBy: "Loading Bay",
  },
  {
    stowage: "103F",
    carrier: "B737 Holloware ISC-MEA",
    equipment: "Atlas Half Size Meal Cart",
    preparedBy: "Spare",
  },
  {
    stowage: "204",
    carrier: "JC Oven",
    equipment: "Oven Atlas - 32 meals (Shelf)",
    preparedBy: "Tray Set Up",
  },
  {
    stowage: "101T",
    carrier: "JC Headsets X12",
    equipment: "Atlas Small Unit Aluminum",
    preparedBy: "Dry Stores",
  },
  {
    stowage: "101B",
    carrier: "Ice",
    equipment: "Atlas Small Unit Aluminum",
    preparedBy: "Loading Bay",
  },
  {
    stowage: "103F",
    carrier: "B737 Holloware ISC-MEA",
    equipment: "Atlas Half Size Meal Cart",
    preparedBy: "Spare",
  },
  {
    stowage: "204",
    carrier: "JC Oven",
    equipment: "Oven Atlas - 32 meals (Shelf)",
    preparedBy: "Tray Set Up",
  },
  {
    stowage: "101T",
    carrier: "JC Headsets X12",
    equipment: "Atlas Small Unit Aluminum",
    preparedBy: "Dry Stores",
  },
  {
    stowage: "101B",
    carrier: "Ice",
    equipment: "Atlas Small Unit Aluminum",
    preparedBy: "Loading Bay",
  },
  {
    stowage: "103F",
    carrier: "B737 Holloware ISC-MEA",
    equipment: "Atlas Half Size Meal Cart",
    preparedBy: "Spare",
  },
  {
    stowage: "204",
    carrier: "JC Oven",
    equipment: "Oven Atlas - 32 meals (Shelf)",
    preparedBy: "Tray Set Up",
  },
  {
    stowage: "101T",
    carrier: "JC Headsets X12",
    equipment: "Atlas Small Unit Aluminum",
    preparedBy: "Dry Stores",
  },
  {
    stowage: "101B",
    carrier: "Ice",
    equipment: "Atlas Small Unit Aluminum",
    preparedBy: "Loading Bay",
  },
  {
    stowage: "103F",
    carrier: "B737 Holloware ISC-MEA",
    equipment: "Atlas Half Size Meal Cart",
    preparedBy: "Spare",
  },
  {
    stowage: "204",
    carrier: "JC Oven",
    equipment: "Oven Atlas - 32 meals (Shelf)",
    preparedBy: "Tray Set Up",
  },
  {
    stowage: "101T",
    carrier: "JC Headsets X12",
    equipment: "Atlas Small Unit Aluminum",
    preparedBy: "Dry Stores",
  },
  {
    stowage: "101B",
    carrier: "Ice",
    equipment: "Atlas Small Unit Aluminum",
    preparedBy: "Loading Bay",
  },
  {
    stowage: "103F",
    carrier: "B737 Holloware ISC-MEA",
    equipment: "Atlas Half Size Meal Cart",
    preparedBy: "Spare",
  },
  {
    stowage: "204",
    carrier: "JC Oven",
    equipment: "Oven Atlas - 32 meals (Shelf)",
    preparedBy: "Tray Set Up",
  },
];
