// export const samplePreparations = [
//   {
//     stowage: "101T",
//     carrier: "JC Headsets X12",
//     equipment: "Atlas Small Unit Aluminum",
//     preparedBy: "Dry Stores",
//   },
//   {
//     stowage: "101B",
//     carrier: "Ice",
//     equipment: "Atlas Small Unit Aluminum",
//     preparedBy: "Loading Bay",
//   },
//   {
//     stowage: "103F",
//     carrier: "B737 Holloware ISC-MEA",
//     equipment: "Atlas Half Size Meal Cart",
//     preparedBy: "Spare",
//   },
//   {
//     stowage: "204",
//     carrier: "JC Oven",
//     equipment: "Oven Atlas - 32 meals (Shelf)",
//     preparedBy: "Tray Set Up",
//   },
//   {
//     stowage: "101T",
//     carrier: "JC Headsets X12",
//     equipment: "Atlas Small Unit Aluminum",
//     preparedBy: "Dry Stores",
//   },
//   {
//     stowage: "101B",
//     carrier: "Ice",
//     equipment: "Atlas Small Unit Aluminum",
//     preparedBy: "Loading Bay",
//   },
//   {
//     stowage: "103F",
//     carrier: "B737 Holloware ISC-MEA",
//     equipment: "Atlas Half Size Meal Cart",
//     preparedBy: "Spare",
//   },
//   {
//     stowage: "204",
//     carrier: "JC Oven",
//     equipment: "Oven Atlas - 32 meals (Shelf)",
//     preparedBy: "Tray Set Up",
//   },
//   {
//     stowage: "101T",
//     carrier: "JC Headsets X12",
//     equipment: "Atlas Small Unit Aluminum",
//     preparedBy: "Dry Stores",
//   },
//   {
//     stowage: "101B",
//     carrier: "Ice",
//     equipment: "Atlas Small Unit Aluminum",
//     preparedBy: "Loading Bay",
//   },
//   {
//     stowage: "103F",
//     carrier: "B737 Holloware ISC-MEA",
//     equipment: "Atlas Half Size Meal Cart",
//     preparedBy: "Spare",
//   },
//   {
//     stowage: "204",
//     carrier: "JC Oven",
//     equipment: "Oven Atlas - 32 meals (Shelf)",
//     preparedBy: "Tray Set Up",
//   },
//   {
//     stowage: "101T",
//     carrier: "JC Headsets X12",
//     equipment: "Atlas Small Unit Aluminum",
//     preparedBy: "Dry Stores",
//   },
//   {
//     stowage: "101B",
//     carrier: "Ice",
//     equipment: "Atlas Small Unit Aluminum",
//     preparedBy: "Loading Bay",
//   },
//   {
//     stowage: "103F",
//     carrier: "B737 Holloware ISC-MEA",
//     equipment: "Atlas Half Size Meal Cart",
//     preparedBy: "Spare",
//   },
//   {
//     stowage: "204",
//     carrier: "JC Oven",
//     equipment: "Oven Atlas - 32 meals (Shelf)",
//     preparedBy: "Tray Set Up",
//   },
//   {
//     stowage: "101T",
//     carrier: "JC Headsets X12",
//     equipment: "Atlas Small Unit Aluminum",
//     preparedBy: "Dry Stores",
//   },
//   {
//     stowage: "101B",
//     carrier: "Ice",
//     equipment: "Atlas Small Unit Aluminum",
//     preparedBy: "Loading Bay",
//   },
//   {
//     stowage: "103F",
//     carrier: "B737 Holloware ISC-MEA",
//     equipment: "Atlas Half Size Meal Cart",
//     preparedBy: "Spare",
//   },
//   {
//     stowage: "204",
//     carrier: "JC Oven",
//     equipment: "Oven Atlas - 32 meals (Shelf)",
//     preparedBy: "Tray Set Up",
//   },
// ];
export const samplePreparations = [
  {
    "id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
    "flightId": "123e4567-e89b-12d3-a456-426614174000",
    "packingStandardId": "98765432-abcd-ef12-3456-7890abcdef12",
    "storageId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    "parentStorageId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    "galleyConfigurationId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    "isContentPrepared": true,
    "isTrackConsumption": false,
    "isDynamicLoadingIncomplete": false,
    "name": "Forward Galley - Trolley 1",
    "nameDisplay": "FWD Galley T1",
    "code": "FWD-T1",
    "position": "Forward",
    "positionRap": "string",
    "rotationCode": "R01",
    "direction": "Inbound",
    "weight": 45.5,
    "availableWeight": 15.3,
    "galleyCode": "FWD",
    "galleyPosition": "Forward Main",
    "preparedBy": "John Doe",
    "priority": 1,
    "equipment": "Half-size trolley",
    "quantity": 2,
    "date": "2025-11-13",
    "qrCode": "string",
    "qrCodeUrl": "https://example.com/qr/abc123",
    "dynamicLoadingQrCode": "string",
    "dynamicLoadingQrCodeUrl": "string",
    "labelUrl": "https://example.com/labels/prep123.pdf",
    "report": "string",
    "sealTagNumber": "SEAL-001234",
    "assemblyProcessFlag": "completed",
    "loadedTruckFlag": "loaded",
    "createdAt": "2025-11-13T10:00:00Z",
    "updatedAt": "2025-11-13T12:30:00Z"
  }
]